/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'km-ranges': KmRange;
    packagings: Packaging;
    'price-zones': PriceZone;
    production_centers: ProductionCenter;
    users: User;
  };
  globals: {};
}
export interface KmRange {
  id: string;
  name?: string;
  start?: string;
  end?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Packaging {
  id: string;
  name?: string;
  'price-zones'?: string[] | PriceZone[];
  unit_of_measure?: 'metric_tonnes' | 'amount';
  updatedAt: string;
  createdAt: string;
}
export interface PriceZone {
  id: string;
  name?: string;
  'km-range': string | KmRange;
  priceType?: 'fixed' | 'perkm';
  price: string;
  updatedAt: string;
  createdAt: string;
}
export interface ProductionCenter {
  id: string;
  name: string;
  address?: string;
  'price-zones': string[] | PriceZone[];
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
